services :
  mongodb:
    image: mongo:noble
    container_name: mongodb
    ports:
    - "27027:27017"  # Map host port 27027 to container port 27017
    volumes:
    - ./mongodb:/data/db
    networks:
      - backend

    restart: always  # Restart the container automatically if it stops

networks:
  backend: